### ISSUE TITLE
建议FWPopupItem增加一个设置字体的属性，而不是在FWPopupViewProperty全局设置

### ISSUE THREAD

**Issue by YouthKnowsNoPain** [choiceyou/FWPopupView#14]

**Comment by choiceyou** [comment]
• v4.0.5:
 1、FWAlertView、FWSheetView、FWDateView 中相关字体默认改为不加粗，即boldSystemFont 改为systemFont；
 2、FWPopupItem中新增itemTitleFont，该属性优先权大于全局变量，如需使用该变量可使用：初始化方法3；

**Comment by YouthKnowsNoPain** [comment]
FWSheetView中是否可以添加单独设置取消按钮的字体颜色和字体大小的属性

**Comment by choiceyou** [comment]
可以增加，还有其他需求吗？

**Comment by YouthKnowsNoPain** [comment]
没有了。感谢！

**Comment by choiceyou** [comment]
• v4.0.6:
1、解决某个类中同时存在两个非懒加载方式的弹窗成员变量，前一个点击外部隐藏时会影响另外一个弹窗显示的问题；
2、FWSheetView：FWSheetViewProperty可设置取消按钮的字体颜色、大小以及背景颜色；
