### ISSUE TITLE
不兼容SnapKit

### ISSUE THREAD

**Issue by HZZJL** [choiceyou/FWPopupView#15]
Compiling for iOS 8.0, but module 'SnapKit' has a minimum deployment target of iOS 10.0: /Users/mac/Library/Developer/Xcode/DerivedData/TLZB-eafleshslmajwzhhtwkwjiuyjvjn/Build/Products/Debug-iphoneos/SnapKit/SnapKit.framework/Modules/SnapKit.swiftmodule/arm64.swiftmodule

**Comment by choiceyou** [comment]
那你可以使用3.1.5版本：pod 'FWPopupView','3.1.5'
