### ISSUE TITLE
更新后ios13后，出现初始化问题

### ISSUE THREAD

**Issue by qiaqiaxian** [choiceyou/FWPopupView#17]
![WX20190921-142021](https://user-images.githubusercontent.com/21219815/65369078-7562ad00-dc7b-11e9-9dad-bea5e4bbb4d5.png)

**Comment by choiceyou** [comment]
升级到：4.0.8即可

**Comment by qiaqiaxian** [comment]
> 升级到：4.0.8即可

感谢，更新得真快！

**Comment by qiaqiaxian** [comment]
你好，一直更新不了什么情况啊？
