### ISSUE TITLE
Cannot invoke initializer for type 'FWPopupWindow' with no arguments

### ISSUE THREAD

**Issue by dslcoding** [choiceyou/FWPopupView#18]
[
![Jietu20190923-215000](https://user-images.githubusercontent.com/26846337/65431601-536c5480-de4c-11e9-89e3-730c27dc2a5e.jpg)
](url)这里编译不通过

**Comment by ouryi-2020** [comment]
额，我也遇到这个问题了，想问问这是什么情况，新手
