### ISSUE TITLE
关于 topCenter - frame

### ISSUE THREAD

**Issue by MuRanJiangXia** [choiceyou/FWPopupView#21]
当为topCenter - frame 样式的时候，能否设置上下maskViewColor 不同呢，
我想要上面是透明颜色，下面有个遮罩颜色
![Simulator Screen Shot - iPhone 8 Plus - 2019-11-05 at 19 09 12](https://user-images.githubusercontent.com/24642593/68203047-f09bda80-ffff-11e9-845e-789420115d08.png)

**Comment by choiceyou** [comment]
FWPopupView暂时没有该属性，可以使用FWPopupViewOC库，该库有个属性：shouldClearSpilthMask
