### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ludy520** [choiceyou/FWPopupView#22]
FWPopupView使用其他版本报Compiling for iOS 8.0, but module 'SnapKit' has a minimum deployment target of iOS 10.0，如果使用3.1.5版本报Cannot invoke initializer for type 'FWPopupWindow' with no arguments，怎么处理？？？

**Comment by choiceyou** [comment]
点击Pods找到SnapKit库：Build Settings 搜索  iOS Deployment Target，修改最低版本为你项目支持的最低版本
