### ISSUE TITLE
导入后运行报错，好像和SnapKit冲突了

### ISSUE THREAD

**Issue by Azraeltulips** [choiceyou/FWPopupView#23]
如果项目中已经导入了SnapKit，再导入这个库，运行会报错

**Comment by Azraeltulips** [comment]
原因是最新的SnapKit库最低支持10.0，而你这个最低支持的8.0。报错：Compiling for iOS 8.0, but module 'SnapKit' has a minimum deployment target of iOS 10.0: ...
我收到将你这个库的最低支持版本改到了10.0，虽然运行成功了，但是不知道会不会有问题

**Comment by choiceyou** [comment]
嗯，可以固定 SnapKit 的版本为 4.x或者你这种解决方案，你这种解决方式目前不知道会不会出现问题
