### ISSUE TITLE
originKeyWindow bug

### ISSUE THREAD

**Issue by 2008muyu** [choiceyou/FWPopupView#25]
这个属性在hide时 makeKey 会导致其他使用keyWindow属性显示不出来。

bug原因：
赋值windows.first 并不是keyWindow
在hide时又做了makeKey操作，导致在使用keyWindow属性时不能被显示。
此处赋值的时机是否应该放在吊起FWPopupSWindow时？
望改进。

**Comment by choiceyou** [comment]
感谢反馈，4.1.4版本已经优化了此问题。
