### ISSUE TITLE
创建弹窗的代码被多次调用，弹窗会有多个

### ISSUE THREAD

**Issue by Azraeltulips** [choiceyou/FWPopupView#27]
期望可以判断一下 如果当前有一个弹窗存在就不要在显示了，就显示当前的就可以了

**Comment by choiceyou** [comment]
我们是支持多个弹窗纯在的。
针对你的问题的解决方案：[FWPopupView isPopupViewHiden] 来判断当前是否有弹窗。

**Comment by Azraeltulips** [comment]
> 我们是支持多个弹窗纯在的。
> 针对你的问题的解决方案：[FWPopupView isPopupViewHiden] 来判断当前是否有弹窗。

好的 谢谢
