### ISSUE TITLE
iPhone竖屏切到横屏时，菜单无法自动调整。

### ISSUE THREAD

**Issue by maxxfire** [choiceyou/FWPopupView#4]
你好，版本3.0.6。用Swift语言在iPhone竖屏时创建一个topCenter居中的菜单FWMenuView。
弹出菜单显示后，将手机从竖屏旋转为横屏，底部遮罩层未做自动调整适应，导致显示位置发生偏移。

**Comment by choiceyou** [comment]
不好意思，目前没有兼容横竖屏切换。

**Comment by Acel-L** [comment]
你现在是加了横竖屏切换吗？ 最新版本我APP页面只支持竖屏点击弹出菜单后 菜单横屏了，但是我的页面还是竖屏的！  建议添加一个属性菜单是否支持自动横竖屏 不然我跟楼主这两种需求不能同时满足

**Comment by ChinaKeep** [comment]
现在横竖屏的时候会导致原有界面错乱
