### ISSUE TITLE
考虑 titleLabel 和 detailLabel 支持直接修改 Font

### ISSUE THREAD

**Issue by CivelXu** [choiceyou/FWPopupView#6]

**Comment by choiceyou** [comment]
你好，请问你问的是哪个组件？FWAlert是支持直接修改 标题、描述 Lable的字体大小的。

**Comment by CivelXu** [comment]
大小可以改 默认都是加粗了




| |
xuxiwen785
邮箱：xuxiwen785@163.com
|

Signature is customized by Netease Mail Master

在2018年10月30日 09:32，choiceyou 写道：

你好，请问你问的是哪个组件？FWAlert是支持直接修改 标题、描述 Lable的字体大小的。

**Comment by Samuel0807** [comment]
titleFontSize和buttonFontSize这几个FWPopupViewProperty属性最好直接设置font， 有时候加粗感觉有点丑
